name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Build Step
      run: |
        echo "Building frontend application..."
        npm install
        npm run build
        
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      env:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          cd /var/www/frontend
          git pull origin main
          npm install
          pm2 restart frontend
          EOF
          rm ssh_key
